#PVM Plugin By TAEmery0
HasBeenSetup: false
#Change This ^^^ To Make The Plugin Active (Puts plugin in "Safe State")
Armor:
  Helmet: LEATHER_HELMET
  Chestplate: LEATHER_CHESTPLATE
  Leggings: LEATHER_LEGGINGS
  Boots: LEATHER_BOOTS
GivenItems: #Up To 10 Items Given
  1: STONE_SWORD
MySQL:
  Host:
  User:
  Password:
  Database:
Lobby:
  x: 0
  y: 100
  z: 0
  w: world
  teleport-on-join: false
Arenas:
  1: 
    x:
    y:
    z:
    w: 
    active: false