#PVM Plugin By TAEmery0
HasBeenSetup: false
#Change This ^^^ To Make The Plugin Active (Puts plugin in "Safe State")
Armor:
  Helmet: LEATHER_HELMET
  Chestplate: LEATHER_CHESTPLATE
  Leggings: LEATHER_LEGGINGS
  Boots: LEATHER_BOOTS
GivenItems: #Up To 10 Items Given
  1: WOODEN_SWORD
MySQL:
  Host:
  User:
  Password:
  Database:
Lobby:
  x: 0
  y: 100
  z: 0
  w: world
  teleport-on-join: false
SwordRanks:
  1:
    Item: STONE_SWORD
    Cost: 75
  2:
    Item: IRON_SWORD
    Cost: 200
  3:
    Item: DIAMOND_SWORD
    Cost: 450
Arenas:
  1: 
    x:
    y:
    z:
    w: 
    active: false