name: PVM
main: me.taemery0.PVM.PVM
version: 2.3.1
database: false
author: TAEmery0 - Tyler Emery
description: Plugin for PVM Arena and Overall Game Management
commands:
  pvm:
    description: Base Command For PVM Plugin
  pvma:
    description: Base Admin Command For PVM Plugin